spring:
  application:
    name: tenpo-backend-challenge

  # R2DBC es parte de spring data para manejar transacciones con webflux
  r2dbc:
    url: ${DATASOURCE_R2DBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  # Flyway permite crear tablas en la db cuando spring boot inicia
  flyway:
    url: ${DATASOURCE_JDBC_URL}
    enabled: true
    locations: classpath:db/migration
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  # Configuracion de REDIS
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


# Configuracion de Swagger con WebFlux
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    configUrl: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Default API

# Configuracion de la API que entrega el porcentaje para usar en el calculo
percentage-api:
  url: ${PERCENTAGE_API_URL}
  uri: ${PERCENTAGE_API_URI}
